// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinBankAPI.Data;

#nullable disable

namespace MinBankAPI.Migrations
{
    [DbContext(typeof(AccountsDbContext))]
    [Migration("20250407092803_BankAccountsWithdrawls")]
    partial class BankAccountsWithdrawls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinBankAPI.Models.BankAccounts", b =>
                {
                    b.Property<long>("idNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idNumber"));

                    b.Property<string>("accountHolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accountStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("availableBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("cellphoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resdentialAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idNumber");

                    b.ToTable("BankAccounts");

                    b.HasData(
                        new
                        {
                            idNumber = 8965234589125L,
                            accountHolderName = "John’s Savings",
                            accountNumber = "6263451278",
                            accountStatus = "Active",
                            accountType = "Savings",
                            availableBalance = 100120.00m,
                            cellphoneNumber = "0123678945",
                            emailAddress = "Johns@gmail.com",
                            resdentialAddress = "12 Smith Avenue, Durban, 3452"
                        },
                        new
                        {
                            idNumber = 95938619222618L,
                            accountHolderName = "Jane’s Fixed",
                            accountNumber = "89652345125",
                            accountStatus = "Active",
                            accountType = "Fixed Deposit",
                            availableBalance = 5000.00m,
                            cellphoneNumber = "0725698945",
                            emailAddress = "jane.doe@gmail.com",
                            resdentialAddress = "13 Windswaeltjie Avenue, Newcastle, 2940"
                        },
                        new
                        {
                            idNumber = 8691190759656L,
                            accountHolderName = "Tanay Transaction",
                            accountNumber = "9876543210",
                            accountStatus = "Active",
                            accountType = "Cheque",
                            availableBalance = 2500.00m,
                            cellphoneNumber = "0745698745",
                            emailAddress = "tanay.kgmail.com",
                            resdentialAddress = "2 Muckelnert Avenue, Durban, 3452"
                        },
                        new
                        {
                            idNumber = 9859082070719L,
                            accountHolderName = "Sanvi Savings",
                            accountNumber = "9876542345",
                            accountStatus = "Active",
                            accountType = "Cheque",
                            availableBalance = 125000.00m,
                            cellphoneNumber = "0750246982",
                            emailAddress = "Johns@gmail.com",
                            resdentialAddress = "3300 LaLucia Ridge Avenue, Cape Town, 7894"
                        },
                        new
                        {
                            idNumber = 8883275546624L,
                            accountHolderName = "Jimmy Cheque",
                            accountNumber = "9876533345",
                            accountStatus = "Inactive",
                            accountType = "Cheque",
                            availableBalance = 125000.00m,
                            cellphoneNumber = "0835698756",
                            emailAddress = "Johns@gmail.com",
                            resdentialAddress = "63 Jane Avenue, Dundee, 8795"
                        },
                        new
                        {
                            idNumber = 9056861318568L,
                            accountHolderName = "Suvashka Jugernath Cheque",
                            accountNumber = "9056861318",
                            accountStatus = "Inactive",
                            accountType = "Cheque",
                            availableBalance = 12005000.00m,
                            cellphoneNumber = "0765158778",
                            emailAddress = "suvashka.kalideen@gmail.com",
                            resdentialAddress = "63 Elachie Avenue, Newcastle, 2940"
                        },
                        new
                        {
                            idNumber = 9356461312518L,
                            accountHolderName = "Sheryl Kalideen Fixed",
                            accountNumber = "9057763318",
                            accountStatus = "Inactive",
                            accountType = "Cheque",
                            availableBalance = 125000.00m,
                            cellphoneNumber = "0845698752",
                            emailAddress = "skali@gmail.com",
                            resdentialAddress = "2 Queensbury Avenue, Durban, 4051"
                        });
                });

            modelBuilder.Entity("MinBankAPI.Models.WithdrawFromAccount", b =>
                {
                    b.Property<long>("idNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idNumber"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("accountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idNumber");

                    b.ToTable("Withdrawals");
                });
#pragma warning restore 612, 618
        }
    }
}
